import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import Link from "next/link";
import Example from "@/component/pagination";

import { faStar } from "@fortawesome/free-solid-svg-icons";
import { FontAwesomeIcon } from "@fortawesome/react-fontawesome";

const inter = Inter({ subsets: ["latin"] });

interface IMovie {
  plot: string;
  genres: [string];
  runtime: Number;
  rated: "NOT RATED" | "RATED";
  cast: [string];
  poster: string;
  title: string;
  fullplot: string;
  languages: [string | Date];
  directors: [string];
  writers: [string];
  released: Date;
  awards: {
    wins: number;
    nominations: number;
    text: number | string;
  };
  lastupdated: Date;
  year: Date;
  imdb: {
    rating: number;
    votes: number;
    id: number;
  };
  countries: [string];
  type: string;
  tomatoes: {
    viewer: {
      rating: number;
      numReviews: number;
      meter: number;
    };
    dvd: Date;
    production: string;
    lastUpdated: Date;
  };
  num_mflix_comments: number;
}

interface IMovies {
  movies: IMovie[];
}

export default function Home({ movies }: IMovies) {
  return (
    <div className=" h-screen ">
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1 className="text-5xl text-center p-8 font-bold">Movies List</h1>
      <div className=" container mx-auto">
        <div className="grid grid-cols-4 container">
          {movies.length > 0 &&
            movies.map((movies, idx) => (
              <div key={idx} className="group card">
                <div className="aspect-[9/12]  group ">
                  <Image
                    src={movies.poster || "/images/zurag.jpeg"}
                    alt="moviePhoto"
                    width={300}
                    height={300}
                    className="w-full h-full object-cover rounded"
                  />
                  <div className=" text-2xl p-5 ">{movies.title}</div>
                  <div className="grid grid-cols-2 mx-auto mb-0 p-2.5">
                    <div className="w-21 text-center mx-2 border-dotted border-2 border-red-700">
                      IMDB:
                      {movies.imdb.rating}%
                    </div>
                    <div className="grid grid-cols-2 border-dotted border-2 border-yellow-500  text-center w-20 mx-20">
                      {movies.tomatoes.viewer.rating}
                      <FontAwesomeIcon
                        className="text-yellow-500 w-5 mx-3"
                        icon={faStar}
                      />
                    </div>
                  </div>
                </div>
              </div>
            ))}
        </div>
        <Example />
      </div>
    </div>
  );
}
export async function getServerSideProps() {
  const result = await fetch("http://localhost:8000/movies");
  const data = await result.json();
  console.log("MOVIES IRLEE", data.movies);
  return { props: { movies: data.movies } };
}
